### ISSUE TITLE
commits 只推送主分支

### ISSUE THREAD

**Issue by Moyuyanli** [gnuf0rce/github-helper#17]

**Comment by cssxsh** [comment]
什么订阅

**Comment by Moyuyanli** [comment]
> 什么订阅

commit  检测其他分支的提交

**Comment by cssxsh** [comment]
你应该给复现条件

**Comment by Moyuyanli** [comment]
原命令:`/<repo-commit> <add> [repo] [contact]?`这个命令只能添加订阅默认分之，对于其他分之不生效。
能否添加一个`/<repo-commit> <add> <tree> [repo] [contact]?`这样的一个命令来实现针对其他分之的commit的检测

**Comment by cssxsh** [comment]
我没有空给你找实验用例

**Comment by cssxsh** [comment]
https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#list-commits

Query parameters `sha`

**Comment by cssxsh** [comment]
`/repo-issue add Moyuyanli/HuYanSession:dev`
