### ISSUE TITLE
[Bug]: Commit 推送信息错误

### ISSUE THREAD

**Issue by QianFuv** [gnuf0rce/github-helper#20]
Commit: https://github.com/Qian-F/Miracles-Journey/commit/d88923f1c0264fcef1a4beeecbff1e8c95bc7258
`58 changed files with 1,063 additions and 656 deletions`
![image](https://github.com/gnuf0rce/github-helper/assets/111696321/9fdbb22d-1939-4272-901e-ac15c2232b54)

**Comment by cssxsh** [comment]
https://api.github.com/repos/Qian-F/Miracles-Journey/commits

https://docs.github.com/en/rest/commits/commits#list-commits

api  未返回对应数据

**Comment by QianFuv** [comment]
应该添加 GithubToken 来解除 API 调用限制？

**Comment by cssxsh** [comment]
这可能是api本身的限制

**Comment by QianFuv** [comment]
![Screenshot_2024-05-11-01-08-41-53_df198e732186825c8df26e3c5a10d7cd.png](https://github.com/gnuf0rce/github-helper/assets/111696321/6e624eb8-3f2a-43f8-a312-9507dd7014a3)

现在试了一下发现可以被调用 github rest api是可以通过添加身份验证token来增加调用次数的 感觉可能还真是这个问题

**Comment by cssxsh** [comment]
和 token 没有直接关系
查证只查一半
我上面的回复里都有文档链接，文档写的明明白白
files 这些内容不是 api 必须提供的内容

**Comment by QianFuv** [comment]
https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#get-a-commit

**Comment by QianFuv** [comment]
![image](https://github.com/gnuf0rce/github-helper/assets/111696321/fea5642d-70df-408e-879b-6c437b1a7e8c)
![image](https://github.com/gnuf0rce/github-helper/assets/111696321/2fc347ef-f8c9-4df1-9024-a52b85b2ddbb)

**Comment by cssxsh** [comment]
我上面说的是 [list-commits](https://docs.github.com/en/rest/commits/commits#list-commits)

**Comment by QianFuv** [comment]
list-commits 好像确实不行
