### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by lqbby** [gnuf0rce/github-helper#3]
最近使用，发现所有添加命令都用不了了
![Screenshot_2021-11-18-20-40-36-135_com sonelli juicessh](https://user-images.githubusercontent.com/93820952/142417498-0f2c8089-9ed3-40ea-be53-9702097a4610.jpg)
这是报错

**Comment by lqbby** [comment]
确定了，换成1.13，没问题，
最新版本就有问题

**Comment by cssxsh** [comment]
命令行模式下，没有指定联系人参数

**Comment by cssxsh** [comment]
匹配 full repo name 的 regex 和 url repo 的regex 变量名一样，编译的时候弄混了
