### ISSUE TITLE
Github团队repo的API数据结构与个人repo的不一样

### ISSUE THREAD

**Issue by leoweyr** [gnuf0rce/github-helper#9]
如图repo-commit订阅的是团队仓库出现的报错，即organization's repo
![image](https://user-images.githubusercontent.com/58080150/179443553-2587112d-6f91-4dd2-a51d-488a06ee697a.png)

**Comment by cssxsh** [comment]
need auth (Personal Access Tokens）
https://github.com/gnuf0rce/github-helper/blob/fcc5443eba6234b1d3a26c98ee7f1e1d35f64e27/readme.md?plain=1#L109-L117
